// 山海经异兽完整数据
// 来源：《山海经》南山经/西山经/北山经/东山经/中山经/海外经/海内经/大荒经 + 附录专题

export interface Creature {
  id: string;
  name: string;
  source: string;
  rawText: string;
  promptZh: string;
  promptEn: string;
  tags: string[];
  bagua: string;
}

// 南山经异兽
const NANSHAN_CREATURES: Creature[] = [
  {
    id: "chi-ru",
    name: "赤鱬",
    source: "《山海经·南山经》",
    rawText: "英水出焉，南流注于即翼之泽。其中多赤鱬，其状如鱼而人面，其音如鸳鸯，食之不疥。",
    promptZh: "生成一张山海经赤鱬插图，人面鱼身的奇异生物在幽蓝湖底游弋，鱼身晶莹透明，人面清晰可辨，周围是水草和珊瑚，远处光斑透入水面，中国神话水中灵兽，水墨彩绘风格。",
    promptEn: "A mystical Chinese creature Chi Ru, Shan Hai Jing illustration, fish with a human face swimming in a deep crystal lake, translucent body showing internal organs, clearly defined humanoid face, coral and seaweed surroundings, light rays penetrating from above, ethereal blue atmosphere, ancient Chinese mythological water spirit, ink wash painting style, no text, no watermark",
    tags: ["南山经", "水族", "祥瑞"],
    bagua: "li",
  },
  {
    id: "li-li",
    name: "狸力",
    source: "《山海经·南山经》",
    rawText: "柜山，有兽焉，其状如豚，有距，其音如狗吠，其名曰狸力，见则其县多土功。",
    promptZh: "生成一张山海经狸力插图，小猪身形却长着锋利的鸡爪，在挖掘泥土，地面隆起堆成小山，尘土飞扬，周围是古代县城的工地，中国上古劳作之兽，水墨淡彩风格。",
    promptEn: "A diligent Chinese beast Li Li, Shan Hai Jing illustration, piglet-sized creature with rooster-like talons digging earth, mounds of soil piling up around it, dust flying in the air, ancient county construction site in background, hardworking mythical creature from Chinese folklore, muted ink wash style with earth tones, no text, no watermark",
    tags: ["南山经", "山兽", "土功"],
    bagua: "xun",
  },
  {
    id: "lei",
    name: "类",
    source: "《山海经·南山经》",
    rawText: "亶爰之山，多水，无草木。有兽焉，其状如狸而有髦，其名曰类，自为牝牡，食者不妒。",
    promptZh: "生成一张山海经类插图，野猫身形却披散长发，雌雄同体的神秘生物在幽暗密林间独行，双性特征模糊难辨，周围是潮湿的亚热带植被，月光透过树叶，中国神话神秘异兽，水墨写意风格。",
    promptEn: "A mysterious Chinese beast Lei, Shan Hai Jing ancient illustration, wildcat-like creature with long flowing hair, androgynous form with ambiguous gender features, prowling through dark dense subtropical forest, moonlight filtering through leaves, fog swirling at its feet, enigmatic Chinese mythological creature, sparse ink wash painting, no text, no watermark",
    tags: ["南山经", "山兽", "神秘"],
    bagua: "xun",
  },
  {
    id: "bo-yi",
    name: "猼訑",
    source: "《山海经·南山经》",
    rawText: "基山，有兽焉，其状如羊，九尾，四耳，其目在背，其名曰猼訑，佩之不畏。",
    promptZh: "生成一张山海经猼訑插图，羊身九尾奇异神兽，背生四耳各朝不同方向，眼睛长在后背，九尾如彩带飘散，周身散发无畏神光，佩之不畏的祥瑞之兽，中国上古神怪画风。",
    promptEn: "A fearless Chinese mythical beast Bo Yi, Shan Hai Jing ancient illustration, goat-like creature with nine flowing tails and four ears on its back, eyes positioned on its back watching all directions, divine fearless glow surrounding it, ethereal mystical atmosphere, ancient Chinese supernatural art, nine tails fanning out dramatically, no text, no watermark",
    tags: ["南山经", "山兽", "祥瑞"],
    bagua: "gen",
  },
  {
    id: "qu-ru",
    name: "瞿如",
    source: "《山海经·南山经》",
    rawText: "祷过之山，有鸟焉，其状如鵁而白首，三足，人面，其名曰瞿如，其鸣自号也。",
    promptZh: "生成一张山海经瞿如插图，白首人面怪鸟，巨爪三足站立于热带果树之上，三只脚的爪子粗壮有力，人面神态安详却透着诡异，白色羽毛在热带阳光下闪着银光，中国神话异鸟。",
    promptEn: "A strange Chinese bird Qu Ru, Shan Hai Jing illustration, white-headed creature with humanoid face, standing on a tropical fruit tree on three powerful talons, serene yet unsettling human expression, silver-white plumage glowing under tropical sunlight, ancient Chinese mythological bird, no text, no watermark",
    tags: ["南山经", "鸟", "人面"],
    bagua: "zhen",
  },
  {
    id: "hu-jiao",
    name: "虎蛟",
    source: "《山海经·南山经》",
    rawText: "祷过之山，泿水出焉。有虎蛟，其状鱼身而蛇尾，其音如鸳鸯，食者不肿，可以已痔。",
    promptZh: "生成一张山海经虎蛟插图，鱼身蛇尾的淡水神兽在清澈山涧中游弋，鳞片泛着青色光泽，蛇尾灵活卷曲，游近水面时发出鸳鸯般的鸣叫，周围是奇花异草的热带山谷，中国神话水族。",
    promptEn: "A Chinese water spirit Hu Jiao, Shan Hai Jing illustration, fish-bodied creature with snake tail swimming in a clear mountain stream, blue-green iridescent scales, flexible snake tail coiling gracefully, making dove-like calls near water surface, exotic flora on lush tropical valley banks, ancient Chinese mythological aquatic creature, no text, no watermark",
    tags: ["南山经", "水族", "药用"],
    bagua: "li",
  },
  {
    id: "chang-you",
    name: "长右",
    source: "《山海经·南山经》",
    rawText: "长右之山，无草木，多水。有兽焉，其状如禺而四耳，其名长右，其音如吟，见则其郡县大水。",
    promptZh: "生成一张山海经长右插图，猕猴身形却生四耳的灵兽，在暴涨的山洪中若隐若现，四耳竖起聆听水声，暴雨如注倾泻而下，洪水即将冲毁远处城郭，中国上古水兆之兽。",
    promptEn: "A flood-omen Chinese beast Chang You, Shan Hai Jing illustration, gibbon-like creature with four oversized ears, half-submerged in a surging mountain flood, four ears pricked up listening to rushing water, torrential rain pouring down, flood waters threatening to engulf distant city, ancient Chinese flood omen creature, dramatic storm atmosphere, no text, no watermark",
    tags: ["南山经", "山兽", "兆水灾"],
    bagua: "kan",
  },
  {
    id: "yong",
    name: "颙",
    source: "《山海经·南山经》",
    rawText: "令丘之山，无草木，多大风。有鸟焉，其状如枭，人面四目，有耳，其名曰颙，其鸣自号也。见则天下大旱。",
    promptZh: "生成一张山海经颙插图，人面四眼的怪枭在枯木上站立，四只眼睛同时睁开凝视四方，猫头鹰身形却透出人类的神情，羽毛在旱灾的干风中飘动，周围是龟裂的旱地，中国上古旱灾预兆之鸟。",
    promptEn: "A ominous Chinese owl-like bird Yong, Shan Hai Jing illustration, human-faced bird with four eyes all wide open staring in different directions, owl body with human-like expression, feathers ruffling in dry drought winds, cracked parched earth beneath, ancient Chinese drought omen bird, desolate atmosphere, no text, no watermark",
    tags: ["南山经", "鸟", "兆旱灾"],
    bagua: "gen",
  },
  {
    id: "lu-shu",
    name: "鹿蜀",
    source: "《山海经·南山经》",
    rawText: "杻阳之山，有兽焉，其状如马而白首，其文如虎，而赤尾，其名曰鹿蜀，佩之不愚。",
    promptZh: "生成一张山海经鹿蜀插图，马身白头却披着老虎斑纹的神秘动物，红色尾巴飘逸如火焰，在热带草原上昂首阔步，周围是巨大的红木林，中国上古瑞兽。",
    promptEn: "A mysterious Chinese beast Lu Shu, Shan Hai Jing illustration, horse-like creature with white head and tiger-stripe pattern on body, fiery red tail flowing behind, striding proudly across savanna-like grassland, surrounded by ancient redwood forest, ancient auspicious Chinese animal, warm earth tones, no text, no watermark",
    tags: ["南山经", "山兽", "祥瑞"],
    bagua: "zhen",
  },
  {
    id: "jiu-wei-hu",
    name: "九尾狐",
    source: "《山海经·南山经》",
    rawText: "青丘之山，有兽焉，其状如狐而九尾，其音如婴儿，能食人；食者不蛊。",
    promptZh: "生成一张山海经九尾狐插图，灵秀的白狐九尾飘散如云雾，周身散发幽蓝灵光，蹲坐于云雾缭绕的山巅，婴儿般的啼鸣回荡，身后是幽蓝月夜的水墨山峦，古韵神秘的中国神怪画风。",
    promptEn: "An ancient Chinese nine-tailed fox Jiu Wei Hu, traditional Shan Hai Jing ink painting, elegant fox with nine flowing tails fanning out dramatically, translucent spirit energy emanating from fur, pale blue-white coloring with amber eyes, surrounded by misty mountain forest, haunting beauty with an unsettling presence, infant-like cry echoing in the mist, classical Chinese mythological aesthetic, no text, no watermark",
    tags: ["南山经", "山兽", "灵兽"],
    bagua: "xun",
  },
];

// 西山经异兽
const XISHAN_CREATURES: Creature[] = [
  {
    id: "qiong-qi",
    name: "穷奇",
    source: "《山海经·西山经》",
    rawText: "邽山，其上有兽焉，其状如牛，猬毛，名曰穷奇，音如嗥狗，是食人。",
    promptZh: "生成一张山海经穷奇插图，全身覆盖刺猬般硬毛的巨型牛形野兽，站在荒山枯树旁，獠牙外露，凶悍的目光穿透夜色，青铜器风格背景，深沉压抑的远古凶兽氛围。",
    promptEn: "A ferocious Chinese mythical beast Qiong Qi, Shan Hai Jing illustration, a massive bull-like creature covered in porcupine-like spines, wild boar-like head with glowing fierce eyes, standing over a torn ancient tree in a desolate mountain, terrifying atmosphere, muted dark earth tones with rust red accents, brutal realism, no text, no watermark",
    tags: ["西山经", "凶兽", "四凶"],
    bagua: "qian",
  },
  {
    id: "lu-wu",
    name: "陆吾",
    source: "《山海经·西山经》",
    rawText: "西南四百里，曰昆仑之丘，是实惟帝之下都，神陆吾司之。其神状虎身而九尾，人面而虎爪；是神也，司天之九部及帝之囿时。",
    promptZh: "生成一张山海经陆吾插图，虎身九尾的人面神君伫立于昆仑天宫门前，金色神光笼罩，虎爪张开，九尾展开如屏，天宫门阙在身后霞光万丈，威严庄重，中国古神话壁画风格。",
    promptEn: "A majestic Chinese guardian deity Lu Wu, Shan Hai Jing illustration, divine tiger body with nine sweeping tails, human face with fierce determined expression, tiger claws outstretched, standing atop Mount Kunlun temple entrance, golden divine glow, celestial palace backdrop, Chinese mythological style, no text, no watermark",
    tags: ["西山经", "神祇", "昆仑"],
    bagua: "kun",
  },
  {
    id: "zheng",
    name: "狰",
    source: "《山海经·西山经》",
    rawText: "章莪之山，无草木，多瑶、碧。所为甚怪。有兽焉，其状如赤豹，五尾一角，其音如击石，其名曰狰。",
    promptZh: "生成一张山海经狰插图，赤红如火焰的豹形神兽，五尾如彩霞般展开，额生独角，碧蓝冰晶般的双眸，身后是怪石嶙峋的瑶碧山峦，极光般的流光在背后闪烁，冷峻空灵的中国山水神话氛围。",
    promptEn: "A fierce Chinese leopard beast Zheng, Shan Hai Jing ancient painting, crimson-red leopard body with five long flowing tails, single horn jutting from forehead, crystalline ice-blue eyes, standing on a cliff of strange rocks, aurora-like light flickering behind, pale blue jade mountains, cold dramatic atmosphere, Chinese mythological style, no text, no watermark",
    tags: ["西山经", "山兽", "五尾"],
    bagua: "dui",
  },
  {
    id: "jiao",
    name: "狡",
    source: "《山海经·西山经》",
    rawText: "玉山，有兽焉，其状如犬而豹文，其角如牛，其名曰狡，其音如吠犬，见则其国大穰。",
    promptZh: "生成一张山海经狡的插图，形状像犬但皮毛如豹纹般华丽，角如牛站立于丰收的田野之间，金色麦浪与祥和的村落在远处，国家丰收的吉兆氛围，中国上古祥瑞之兽。",
    promptEn: "A lucky Chinese mythical beast Jiao, Shan Hai Jing illustration, dog-like creature with stunning leopard pattern fur, curved ox-like horns, standing proudly in a golden bountiful wheat field, prosperous villages in distance, national abundance omen atmosphere, warm harvest colors, ancient Chinese auspicious beast, no text, no watermark",
    tags: ["西山经", "山兽", "祥瑞"],
    bagua: "xun",
  },
  {
    id: "jue-ru",
    name: "玃如",
    source: "《山海经·西山经》",
    rawText: "至于翼望之山，有兽焉，其状如狐，而白尾长耳，名曰玃如。",
    promptZh: "生成一张山海经玃如插图，白色皮毛狐狸般身形，却拥有超长的白色大耳和飘逸的白尾巴，在云雾缭绕的山岭间腾空跳跃，姿态轻盈灵动，中国神话中的山间灵兽。",
    promptEn: "A nimble Chinese mountain spirit Jue Ru, Shan Hai Jing ancient painting, fox-like white furred creature with extraordinarily long white ears and a long flowing white tail, leaping gracefully through misty mountain peaks, ethereal agile pose frozen mid-air, light and ethereal atmosphere, ancient Chinese mountain sprite aesthetic, no text, no watermark",
    tags: ["西山经", "山兽", "轻盈"],
    bagua: "zhen",
  },
  {
    id: "luo-yu",
    name: "蠃鱼",
    source: "《山海经·西山经》",
    rawText: "邽山，蒙水出焉，南流注于洋水，其中多黄贝；蠃鱼，鱼身而鸟翼，音如鸳鸯，见则其邑大水。",
    promptZh: "生成一张山海经蠃鱼插图，巨大蠃鱼掠过古代村庄上空，鱼身鳞片闪烁着彩虹光晕，展开的巨翼卷起风暴大雨，远处村庄已被洪水包围，水墨彩绘技法，幽暗压抑的色调和冷蓝高光。",
    promptEn: "A mythical amphibious creature Luo Yu, ancient Shan Hai Jing style, fish body covered in iridescent scales with large bird wings emerging, flying over a flooding ancient Chinese village, whale-sized wings creating storm winds, elegant and ominous, watercolor ink painting technique, muted ink tones with cool blue highlights, heavy rain and flood waters below, no text, no watermark",
    tags: ["西山经", "水族", "兆水灾"],
    bagua: "kan",
  },
  {
    id: "fei-yi-xi",
    name: "肥遗（蛇）",
    source: "《山海经·西山经》",
    rawText: "太华之山，有蛇焉，名曰肥遗，六足四翼，见则天下大旱。",
    promptZh: "生成一张山海经肥遗旱蛇插图，通体赤红的六足四翼巨蛇在干涸龟裂的大地上空盘旋，周围是大地的裂缝和枯死的庄稼，赤地千里，太阳炽烈烤照，蛇身散发焦灼热浪，中国上古旱灾预兆之蛇。",
    promptEn: "A terrifying drought-causing serpent Fei Yi, Shan Hai Jing ancient illustration, crimson six-legged four-winged enormous snake coiling above cracked scorched earth, surroundings showing dead crops and deep fissures in the ground, entire landscape parched and burning under harsh sun, ancient Chinese drought omen creature, no text, no watermark",
    tags: ["西山经", "蛇", "兆旱灾"],
    bagua: "li",
  },
  {
    id: "huan",
    name: "讙",
    source: "《山海经·西山经》",
    rawText: "翼望山中有一种野兽，形状像一般的野猫，只长着一只眼睛却是三条尾巴，名称是讙，发出的声音好像能赛过一百种动物的鸣叫。",
    promptZh: "生成一张山海经讙异兽插图，独眼野猫身形却长着三条蓬松飘逸的大尾巴，在月圆之夜仰天长啸，声波化为可见的涟漪扩散，远处传来百兽呜鸣的回音，中国神话中的奇声之兽。",
    promptEn: "A mysterious Chinese beast Huan, Shan Hai Jing ancient illustration, cat-like creature with a single large eye and three enormous fluffy tails, howling under a full moon, sound waves visualized as rippling rings spreading outward, echoing calls of a hundred beasts in distance, night wind blowing the three tails dramatically, Shan Hai Jing single-eye creature, no text, no watermark",
    tags: ["西山经", "山兽", "奇声"],
    bagua: "gen",
  },
  {
    id: "ying-zhao",
    name: "英招",
    source: "《山海经·西山经》",
    rawText: "槐江之山，有神，英招是其神，马身而人面，虎纹而鸟翼，音如榴。是替天帝看花园的神。",
    promptZh: "生成一张山海经英招神祇插图，人面的英武男子身形却与马身融为一体，全身覆盖老虎斑纹，双翼展开如大鹏，站立于天帝的花园之中，身后是天界瑶草奇花，中国神话中的天帝园丁神。",
    promptEn: "A divine Chinese celestial guardian Ying Zhao, Shan Hai Jing ancient illustration, powerful human-faced deity merged with a majestic horse body, tiger-stripe patterns across the body, enormous bird-like wings spread wide, standing in the Emperor's heavenly garden, celestial flowers and rare herbs behind, divine Shan Hai Jing god of paradise gardens, no text, no watermark",
    tags: ["西山经", "神祇", "天帝之园"],
    bagua: "dui",
  },
  {
    id: "dang-hu",
    name: "当扈",
    source: "《山海经·西山经》",
    rawText: "上申之山，其鸟多当扈，其状如雉，以其髯飞，食之不眴目。",
    promptZh: "生成一张山海经当扈异鸟插图，形状像野鸡，却用胡须化作的翅膀在空中飘飞，羽毛色彩斑斓，眼睛明亮有神，栖息于上申山的云雾松林之间，中国神话中的神奇飞鸟。",
    promptEn: "A magical Chinese bird Dang Hu, Shan Hai Jing illustration, bird shaped like a colorful pheasant but flying using whisker-tendrils as wings instead of feathered ones, brilliant plumage, bright expressive eyes, perched in misty pine forest of ancient Shan Hai Jing mountain, ethereal atmosphere, no text, no watermark",
    tags: ["西山经", "鸟", "以髯飞"],
    bagua: "gen",
  },
  {
    id: "di-jiang",
    name: "帝江",
    source: "《山海经·西山经》",
    rawText: "天山，有神焉，其状如黄囊，赤如丹火，六足四翼，浑敦无面目，是识歌舞，实惟帝江也。",
    promptZh: "生成一张山海经帝江插图，形状像黄色布口袋的红色神球，六只脚四只翅膀在空中旋转起舞，没有眼睛鼻子却能歌善舞，天山之巅的混沌之神，中国上古创世神话中的原初生命，水墨写意风格。",
    promptEn: "A primordial Chinese deity Di Jiang, Shan Hai Jing ancient illustration, formless spherical creature shaped like a yellow cloth sack, glowing red like fire, six legs and four wings rotating in a dance, faceless yet dancing gracefully, cosmic chaos deity from ancient Chinese creation myth, sparse ink wash style, no text, no watermark",
    tags: ["西山经", "神祇", "混沌"],
    bagua: "qian",
  },
  {
    id: "ao-yin",
    name: "獓狠",
    source: "《山海经·西山经》",
    rawText: "钟山，有神焉，其名为烛阴，烛龙之身……（獓狠，状如牛，长四角，披蓑衣般长毛，上古十大凶兽之一）",
    promptZh: "生成一张山海经獓狠插图，巨牛身形覆盖数米长的蓑衣般毛发，四只角如金字塔排列，在幽暗的地府边缘行走，周围是冥界特有的幽蓝色雾气和枯死的不死树，中国上古凶兽。",
    promptEn: "A terrifying ancient Chinese beast Ao Yin, Shan Hai Jing illustration, colossal bull-like creature covered in extremely long matted fur like straw raincoat, four horns arranged in pyramid formation, walking at the edge of the underworld, surrounded by ghostly blue mist and withered immortal trees, ancient Chinese mythological fierce beast, dark atmospheric tones, no text, no watermark",
    tags: ["西山经", "凶兽", "上古"],
    bagua: "kun",
  },
  {
    id: "bo",
    name: "驳",
    source: "《山海经·西山经》",
    rawText: "中曲之山，有兽焉，其状如马而白身，黑尾，一角，虎牙爪，音如鼓音，是食虎豹。",
    promptZh: "生成一张山海经驳插图，白身黑马独角的神骏站在虎豹的尸体旁，昂首嘶鸣，独角锋利如矛，周围是被撕裂的猛兽，它的身后是雪山和荒原，中国上古战伐之兽，威猛无比。",
    promptEn: "A mighty Chinese mythical beast Bo, Shan Hai Jing illustration, pure white horse-like creature with black tail and single sharp horn, standing over fallen tigers and leopards, neighing proudly, horn sharp like a spear, snow-capped mountains and desolate plains behind, ancient Chinese beast that conquers predators, dramatic powerful atmosphere, no text, no watermark",
    tags: ["西山经", "神兽", "食虎豹"],
    bagua: "zhen",
  },
  {
    id: "shu-si",
    name: "数斯",
    source: "《山海经·西山经》",
    rawText: "皋涂之山，有鸟焉，其状如鸦而人足，名曰数斯，食之已瘿。",
    promptZh: "生成一张山海经数斯插图，乌鸦外形却长着粗壮的人脚在岩石上栖息，黑色羽毛泛着金属光泽，人脚粗大有力，周围是布满青苔的岩石和药草，中国神话医食之鸟。",
    promptEn: "A medicinal Chinese bird Shu Si, Shan Hai Jing illustration, crow-like black bird with thick human-like feet resting on mossy rocks, metallic sheen on feathers, medicinal herbs growing around, ancient healing bird from Chinese mythology, dark atmospheric tones, no text, no watermark",
    tags: ["西山经", "鸟", "药用"],
    bagua: "dui",
  },
  {
    id: "luan-niao",
    name: "鸾鸟",
    source: "《山海经·西山经》",
    rawText: "女床之山，有鸟焉，其状如翟而五采文，名曰鸾鸟，见则安宁。",
    promptZh: "生成一张山海经鸾鸟神鸟插图，五彩斑斓的羽翼展开如彩虹降临，赤橙黄绿青蓝紫各色羽毛交织，头戴华冠立于山巅，群鸟围绕，中国神话中的瑞鸟之王，水墨重彩风格。",
    promptEn: "A divine Chinese Luan bird, Shan Hai Jing illustration, magnificent bird with rainbow-colored plumage in red orange yellow green cyan blue violet, wearing a royal crown-like crest, perched on a mountain summit, smaller birds surrounding in reverence, king of auspicious birds in Chinese mythology, rich watercolor ink painting, no text, no watermark",
    tags: ["西山经", "鸟", "祥瑞"],
    bagua: "li",
  },
  {
    id: "ju-fu",
    name: "举父",
    source: "《山海经·西山经》",
    rawText: "崇吾之山，有兽焉，其状如猕猴，手臂上有花纹，尾和豹尾相似，善于跳跃，名叫举父。举父善于投掷，虎豹都害怕他。",
    promptZh: "生成一张山海经举父异兽插图，外形像猕猴但手臂有神秘花纹，尾巴似豹尾蓬松有力，正将一块巨石投掷向虎豹，手臂肌肉紧绷，巨石划破空气，同一时间虎豹惊恐逃窜，中国上古最原始的力量之兽。",
    promptEn: "A powerful Chinese beast Ju Fu, Shan Hai Jing ancient illustration, gibbon-like creature with mysterious patterned arms and leopard-like fluffy tail, hurling an enormous boulder at fleeing tigers and leopards, arm muscles tensed, boulder streaking through air, predators in panic escape, ancient Chinese primal strength creature, no text, no watermark",
    tags: ["西山经", "山兽", "力大"],
    bagua: "gen",
  },
];

// 北山经异兽
const BEISHAN_CREATURES: Creature[] = [
  {
    id: "tian-gou",
    name: "天狗",
    source: "《山海经·北山经》",
    rawText: "阴山，有兽焉。其状如狸而白首，名曰天狗，其音如榴榴，可以御凶。",
    promptZh: "生成一张山海经天狗插图，白首黑身的灵兽蹲踞于山巅巨石之上，仰望满月，发出嘹亮的嚎叫，声波震散云层，守护者的姿态，传统水墨山石背景，极简中国古风。",
    promptEn: "A celestial Chinese guardian beast Tian Gou, Shan Hai Jing illustration, creature with white fox-like head on a dark feline body, perched alert on a mountain peak under a full moon, emitting a resonant cry that ripples the clouds, sacred guardian aesthetic, traditional ink wash painting style, stark contrast between white and black, no text, no watermark",
    tags: ["北山经", "山兽", "御凶"],
    bagua: "kan",
  },
  {
    id: "ya-yu",
    name: "窫窳",
    source: "《山海经·北山经》",
    rawText: "少咸之山，有兽焉，其状如牛而赤身、人面、马足，名曰窫窳，其音如婴儿，是食人。",
    promptZh: "生成一张山海经窫窳插图，牛身红鳞却长着人面和马蹄的恐怖异兽，在月色下的人迹罕至的山谷中缓步前行，婴儿般的啼哭声回荡，人面表情冷漠而诡异，中国上古食人凶兽。",
    promptEn: "A terrifying Chinese monster Ya Yu, Shan Hai Jing ancient illustration, bull-like creature with red scaled body, human face and horse hooves, walking slowly through a desolate moonlit valley, eerie infant cries echoing, expressionless human face conveying deep unease, ancient Chinese man-eating beast, dark atmospheric tones, no text, no watermark",
    tags: ["北山经", "凶兽", "食人"],
    bagua: "qian",
  },
  {
    id: "zhu-huai",
    name: "诸怀",
    source: "《山海经·北山经》",
    rawText: "北岳之山，多枳棘、刚木。有兽焉，其状如牛，而四角、人目、彘耳，其名曰诸怀，其音如鸣雁，是食人。",
    promptZh: "生成一张山海经诸怀插图，野牛身形却头生四角、人目猪耳的恐怖异兽，四角尖锐如刀，人目布满血丝，在荒凉的山间奔跑，雁鸣般的叫声回荡，中国上古食人之兽。",
    promptEn: "A terrifying Chinese beast Zhu Huai, Shan Hai Jing ancient illustration, wild bull-like creature with four sharp horns, human eyes and pig ears, bloodshot human eyes, running through desolate mountains, goose-like cries echoing, ancient Chinese man-eating beast, dark dramatic atmosphere, no text, no watermark",
    tags: ["北山经", "凶兽", "食人"],
    bagua: "kan",
  },
  {
    id: "pao-xiao",
    name: "狍鸮（饕餮）",
    source: "《山海经·北山经》",
    rawText: "钩吾之山，其上多玉，其下多铜。有兽焉，其状如羊身人面，其目在腋下，虎齿人爪，其音如婴儿，名曰狍鸮，是食人。",
    promptZh: "生成一张山海经狍鸮（饕餮）插图，羊身人面的凶兽融合怪物，眼睛在腋下，虎齿狰狞外露，青铜饕餮纹覆满全身，站在祭祀祭坛前，背景有古玉片和青铜器，肃杀诡异的商周祭祀氛围。",
    promptEn: "A terrifying Chinese gluttonous beast Pao Xiao, Shan Hai Jing illustration, grotesque fusion of human face on goat body, eyes positioned unnaturally in the armpit area, exposed tiger-like fangs and claw hands, massive hungry expression, intricate bronze mask pattern texture on skin, dark ritual atmosphere, sacrificial altar background with ancient jade tablets, Chinese mythology, no text, no watermark",
    tags: ["北山经", "凶兽", "食人"],
    bagua: "qian",
  },
  {
    id: "fei-yi-bei",
    name: "肥遗（蛇·北山经）",
    source: "《山海经·北山经》",
    rawText: "浑夕之山，有蛇，一首两身，名曰肥遗，见则其国大旱。",
    promptZh: "生成一张山海经北山经肥遗插图，一个脑袋两个身子的赤红巨蛇在干旱龟裂的国土上蠕动，两个蛇身分叉处清晰可见，周围是枯死的农作物和逃难的人群，中国上古旱灾预兆之蛇。",
    promptEn: "A drought-causing serpent Fei Yi of the northern mountains, Shan Hai Jing illustration, crimson snake with one head and two bodies crawling across parched cracked land, two serpent bodies clearly diverging from the neck, withered crops and fleeing refugees around, ancient Chinese national drought omen, grim desolate atmosphere, no text, no watermark",
    tags: ["北山经", "蛇", "兆旱灾"],
    bagua: "kan",
  },
  {
    id: "he-luo-yu",
    name: "何罗鱼",
    source: "《山海经·北山经》",
    rawText: "谯明之山，谯水出焉。有何罗之鱼，一首而十身，其音如吠犬，食之已痈。",
    promptZh: "生成一张山海经何罗鱼插图，一个脑袋十个身子的奇异鱼类在黄河中翻涌，十个鱼身缠绕在一起却各自游动，发出犬吠般的叫声，鱼身在阳光下闪烁，中国上古十身怪鱼。",
    promptEn: "A strange Chinese fish He Luo Yu, Shan Hai Jing illustration, fish with one head and ten bodies swimming in the Yellow River, ten serpentine bodies tangled yet moving independently, making dog-barking sounds, iridescent scales glinting in sunlight, ancient Chinese ten-bodied fish monster, dramatic river atmosphere, no text, no watermark",
    tags: ["北山经", "水族", "奇鱼"],
    bagua: "li",
  },
  {
    id: "yu",
    name: "寓鸟",
    source: "《山海经·北山经》",
    rawText: "虢山，有鸟焉，状如鼠而鸟翼，其音如羊，可以御兵。",
    promptZh: "生成一张山海经寓鸟插图，鼠身鸟翼的奇异生物在古战场上空盘旋，翅膀像蝙蝠又像鸟，在防御工事上方飞舞，兵灾来临时它出现可以化解，中国上古防御之鸟。",
    promptEn: "A defensive Chinese bird Yu, Shan Hai Jing illustration, mouse-bodied creature with bat-bird wings, circling above ancient battle fortifications, wings spread wide over defensive walls, appearing during wars to ward off disaster, ancient Chinese protective bird, dramatic war-defensive atmosphere, no text, no watermark",
    tags: ["北山经", "鸟", "御兵"],
    bagua: "gen",
  },
  {
    id: "er-shu",
    name: "耳鼠",
    source: "《山海经·北山经》",
    rawText: "丹重之山，有兽焉，其状如鼠，而菟首麋身，其音如獋犬，以其尾飞，食之不采，又可以御百毒。",
    promptZh: "生成一张山海经耳鼠插图，兔子头麋鹿身的奇异小兽用尾巴当螺旋桨在空中飞舞，尾巴旋转发出嗡嗡声，在有毒虫的深山老林中穿梭，中国上古解毒神兽。",
    promptEn: "A magical Chinese flying rodent Er Shu, Shan Hai Jing illustration, tiny creature with rabbit head and elk body, using its tail as a propeller spinning rapidly to fly through dense poisonous forests, buzzing tail sound, ancient Chinese antidote beast, lush dangerous jungle atmosphere, no text, no watermark",
    tags: ["北山经", "异兽", "御毒"],
    bagua: "xun",
  },
  {
    id: "suan-yu",
    name: "酸与",
    source: "《山海经·北山经》",
    rawText: "景山，有鸟焉，其状如蛇，而四翼、六目、三足，名曰酸与，其鸣自詨，见则其邑有恐。",
    promptZh: "生成一张山海经酸与插图，四翼六目三足的怪异鸟类与蛇形身体在空中纠缠，六只眼睛同时注视不同方向，四翼扇动发出恐怖的声音，在瘟疫横行的城邑上空盘旋，中国上古恐慌之鸟。",
    promptEn: "A terrifying Chinese bird Suan Yu, Shan Hai Jing illustration, snake-like creature with four wings, six eyes staring in different directions, three taloned legs, six eyes all watching simultaneously, four wings flapping with ominous sound, circling above plague-stricken ancient city, ancient Chinese fear-inducing creature, dark grim atmosphere, no text, no watermark",
    tags: ["北山经", "凶鸟", "恐慌"],
    bagua: "gen",
  },
  {
    id: "fei-shu",
    name: "飞鼠",
    source: "《山海经·北山经》",
    rawText: "天池之山，有兽焉，其状如兔而鼠首，以其背飞，其名曰飞鼠。",
    promptZh: "生成一张山海经飞鼠插图，兔子身形老鼠头的小兽展开背部的皮膜在夜空飞翔，如滑翔伞般穿梭于星月之间，在天池山的高空盘旋，中国上古飞行异兽。",
    promptEn: "A flying Chinese mammal Fei Shu, Shan Hai Jing illustration, rabbit-sized creature with mouse head, gliding through starry night sky using wing-membranes on its back like a hang glider, soaring between moon and stars above Mount Tianchi, ancient Chinese flying mammal, ethereal night atmosphere, no text, no watermark",
    tags: ["北山经", "异兽", "飞行"],
    bagua: "kan",
  },
  {
    id: "shan-jun",
    name: "山犭军",
    source: "《山海经·北山经》",
    rawText: "岳法之山，有兽焉，其状如犬而人面，善投，见人则笑，其名山犭军，其行如风，见则天下大风。",
    promptZh: "生成一张山海经山犭军插图，狗身人面的敏捷异兽在暴风中高速奔跑，身后卷起旋涡般的尘柱，手持巨石准备投掷，大风呼啸席卷枯草，中国上古风兆之兽。",
    promptEn: "A swift Chinese beast Shan Jun, Shan Hai Jing illustration, dog-like creature with human face sprinting through a violent storm, dust devils swirling behind it, clutching a boulder ready to throw, gale winds howling through withered grass, ancient Chinese wind-omen beast, dramatic wind-storm atmosphere, no text, no watermark",
    tags: ["北山经", "异兽", "兆大风"],
    bagua: "zhen",
  },
  {
    id: "jing-wei",
    name: "精卫",
    source: "《山海经·北山经》",
    rawText: "发鸠之山，有鸟焉，其状如乌，文首，白喙，赤足，名曰精卫。其鸣自詨。是炎帝之少女，名曰女娃。女娃游于东海，溺而不返，故为精卫，常衔西山木石，以堙于东海。",
    promptZh: "生成一张山海经精卫填海插图，小鸟如乌鸦却头有花纹、白喙红足，嘴中衔着巨大的木石奋力飞向东海，波涛汹涌的大海与小鸟形成强烈对比，不屈的意志凝固在永恒的填海之旅中，中国上古悲壮神话。",
    promptEn: "A tiny brave bird Jing Wei, Shan Hai Jing ancient illustration, small crow-like bird with patterned head white beak and red legs, carrying enormous wooden branch and stone in its beak, flying determinedly toward the vast East Sea, turbulent waves dwarfing the tiny bird, spirit of perseverance frozen in eternal mission to fill the sea, Chinese mythological tragic heroine bird, no text, no watermark",
    tags: ["北山经", "鸟", "悲壮"],
    bagua: "li",
  },
  {
    id: "bo-yu",
    name: "薄鱼",
    source: "《山海经·北山经》",
    rawText: "浮戏山，有薄鱼，其状如鳣鱼而一目，其音如欧，见则天下大旱。",
    promptZh: "生成一张山海经薄鱼插图，单眼巨鱼浮现在干涸见底的河床上，独眼浑浊却透着诡异，鱼身在龟裂的泥土中挣扎，周围是死去的鱼虾和枯死的水草，中国上古旱灾凶鱼。",
    promptEn: "A drought-omenous single-eyed Chinese fish Bo Yu, Shan Hai Jing illustration, one-eyed giant fish stranded on a dried-up riverbed, murky single eye radiating malice, body struggling in cracked mud, dead fish and withered reeds around, ancient Chinese severe drought fish, grim desolate atmosphere, no text, no watermark",
    tags: ["北山经", "水族", "兆旱灾"],
    bagua: "kan",
  },
  {
    id: "ming-she",
    name: "鸣蛇",
    source: "《山海经·北山经》",
    rawText: "鲜山，有鸣蛇焉，其状如蛇而四翼，其音如磬，见则其邑大旱。",
    promptZh: "生成一张山海经鸣蛇插图，四翼巨蛇在干旱龟裂的大地上空盘旋，四翼像磬石一样发出和谐的鸣响，蛇身在干燥的热风中滑行，周围是枯死的农作物，中国上古旱灾之蛇。",
    promptEn: "A drought-causing Chinese winged snake Ming She, Shan Hai Jing illustration, four-winged giant serpent coiling above parched cracked earth, wings making melodic stone-chime sounds, dry hot winds blowing, withered crops around, ancient Chinese drought omen serpent, harsh barren landscape atmosphere, no text, no watermark",
    tags: ["北山经", "蛇", "兆旱灾"],
    bagua: "xun",
  },
];

// 东山经异兽
const DONGSHAN_CREATURES: Creature[] = [
  {
    id: "li",
    name: "鱷",
    source: "《山海经·东山经》",
    rawText: "嶧臯之山，有兽焉，其状如鱷鱼而蛇首，其名曰鱷。",
    promptZh: "生成一张山海经鱷异兽插图，鱼身却长着蛇的脑袋，在东山的深潭中潜伏，鳞片泛着幽暗的青光，蛇首在水面若隐若现，冷血爬行类的冷漠眼神，中国上古水族异兽。",
    promptEn: "A mysterious Chinese river beast Li, Shan Hai Jing illustration, fish-bodied creature with snake head lurking in deep eastern mountain pool, dark blue-green iridescent scales, snake head emerging from water surface, cold reptilian gaze, ancient Chinese aquatic monster, murky deep pool atmosphere, no text, no watermark",
    tags: ["东山经", "水族", "蛇首"],
    bagua: "gen",
  },
  {
    id: "lu-mi",
    name: "闾麋",
    source: "《山海经·东山经》",
    rawText: "尸水之上，有兽焉，其状如龙身而人面，是食人。",
    promptZh: "生成一张山海经闾麋插图，龙形身躯却长着人类面孔的恐怖异兽，鳞片泛着幽冷青光，人面表情冷漠而诡异，潜伏于尸水之畔，周围是死亡的水草和雾气，中国上古食人凶龙。",
    promptEn: "A terrifying Chinese man-eating beast Lu Mi, Shan Hai Jing illustration, dragon-bodied creature with humanoid face, cold blue-green scaled body, expressionless human face conveying deep malice, lurking by尸水 (corpse water), dead water plants and fog around, ancient Chinese man-eating aquatic dragon, dark grim atmosphere, no text, no watermark",
    tags: ["东山经", "龙", "食人"],
    bagua: "kan",
  },
  {
    id: "zhu-ru",
    name: "朱獳",
    source: "《山海经·东山经》",
    rawText: "史稿之山，有兽焉，其状如人而彘鬣，穴居而冬蛰，其名曰朱獳。",
    promptZh: "生成一张山海经朱獳插图，人形却长着猪鬃般毛发和狗尾巴的异兽，从东山洞穴中探出头来，猪鬃在冬日寒风中飘动，洞穴幽深黑暗，冬季雪景背景，中国上古穴居异兽。",
    promptEn: "A mysterious Chinese cave beast Zhu Ru, Shan Hai Jing illustration, humanoid creature with wild boar-like bristles and dog tail emerging from a mountain cave, bristles ruffling in winter wind, deep dark cave behind, snowy winter mountain backdrop, ancient Chinese subterranean creature, cold wintry atmosphere, no text, no watermark",
    tags: ["东山经", "穴居", "冬蛰"],
    bagua: "zhen",
  },
  {
    id: "xiang-she",
    name: "象蛇",
    source: "《山海经·东山经》",
    rawText: "少室之山，有象蛇，其状如蛇而赤首白身，其音如呼。",
    promptZh: "生成一张山海经象蛇插图，通体银白唯独头部赤红的奇异之蛇在少室山的岩石间穿行，红色蛇首格外醒目，叫声化为可见的声波在山谷回荡，周围是秋季红叶的少室山景，中国上古赤首怪蛇。",
    promptEn: "A striking Chinese serpent Xiang She, Shan Hai Jing illustration, silver-white serpent body with vivid crimson head slithering through rocky mountain pass, red snake head especially eye-catching, echoing calls visualized as rippling sound waves in the valley, autumn maple-covered mountain backdrop, ancient Chinese red-headed strange snake, vibrant contrast, no text, no watermark",
    tags: ["东山经", "蛇", "赤首"],
    bagua: "gen",
  },
  {
    id: "you-an",
    name: "幽鴳",
    source: "《山海经·东山经》",
    rawText: "幽山，有鸟焉，其状如凫而人面，有翼，见人则佯死，其名曰幽鴳。",
    promptZh: "生成一张山海经幽鴳插图，野鸭身形却长着人类面孔的奇异之鸟，翅膀展开露出人面，假装死在幽山密林之中，旁边有人类猎人靠近浑然不觉，中国上古装死之鸟。",
    promptEn: "A cunning Chinese bird You An, Shan Hai Jing illustration, duck-shaped bird with a human face on its body, wings spread revealing the face, feigning death on the forest floor of a dark mountain, human hunter approaching unaware, ancient Chinese play-dead bird, dark forest atmosphere, no text, no watermark",
    tags: ["东山经", "鸟", "装死"],
    bagua: "xun",
  },
  {
    id: "meng-ji",
    name: "孟极",
    source: "《山海经·东山经》",
    rawText: "蔓渠之山，有兽焉，其状如豹文，而人面，其名曰孟极，昼伏夜行。",
    promptZh: "生成一张山海经孟极插图，豹形野兽身上披着独特花纹却长着人类面孔，在月夜下的东山密林中穿行，花纹在月光下若隐若现，人面透着机警，洞穴在身后若隐若现，中国上古夜行之兽。",
    promptEn: "A nocturnal Chinese beast Meng Ji, Shan Hai Jing illustration, leopard-like creature with distinctive pattern and human face, prowling through eastern mountain forest under moonlight, pattern flickering in moonlight, alert human-like expression, cave entrance glimpsed behind, ancient Chinese night-prowling beast, eerie moonlit forest atmosphere, no text, no watermark",
    tags: ["东山经", "夜行", "豹纹"],
    bagua: "zhen",
  },
  {
    id: "ao",
    name: "驁",
    source: "《山海经·东山经》",
    rawText: "高等家之山，有兽焉，其状如牛而四角，人目彘耳，其名曰驁。",
    promptZh: "生成一张山海经驁插图，牛形巨兽却四角如四把弯刀般张开，人的眼睛透着智慧，猪的耳朵扇动，在东山草原上低头吃草，四角在夕阳下投射出长长的影子，中国上古四角异牛。",
    promptEn: "A massive Chinese four-horned beast Ao, Shan Hai Jing illustration, bull-like creature with four curved horns like scimitars, human-like intelligent eyes, pig ears flapping, grazing on eastern mountain grassland, horns casting long shadows under sunset, ancient Chinese four-horned ox, warm sunset atmosphere, no text, no watermark",
    tags: ["东山经", "牛", "四角"],
    bagua: "gen",
  },
  {
    id: "tian-ying",
    name: "天鹰",
    source: "《山海经·东山经》",
    rawText: "剞上之山，有鸟焉，其状如乌而人面，浴室之逢。",
    promptZh: "生成一张山海经天鹰插图，乌鸦外形却长着人类面孔的神鸟在东山沼泽中悠然沐浴，羽毛在沼泽水汽中泛着灵光，人面透着神圣不可侵犯的气息，周围是芦苇和荷花，中国上古泽国神鸟。",
    promptEn: "A divine Chinese marsh bird Tian Ying, Shan Hai Jing illustration, crow-like bird with human face bathing gracefully in eastern mountain marsh, feathers glowing with spirit light in the mist, sacred human expression conveying divine presence, reeds and lotus flowers around, ancient Chinese marshland deity bird, serene misty atmosphere, no text, no watermark",
    tags: ["东山经", "鸟", "泽神"],
    bagua: "dui",
  },
  {
    id: "ju-ji",
    name: "居暨",
    source: "《山海经·东山经》",
    rawText: "柱山，有兽焉，其状如牛而赤，在市朝。",
    promptZh: "生成一张山海经居暨插图，通体赤红的牛形异兽站在古代市集广场上，路人惊恐四散，赤红皮毛在日光下如燃烧般醒目，威严而诡异的中国上古赤牛。",
    promptEn: "A red Chinese ox spirit Ju Ji, Shan Hai Jing illustration, completely crimson bull-like beast standing in ancient marketplace square, startled townspeople fleeing in all directions, red fur glowing like fire under sunlight, dignified yet eerie presence, ancient Chinese supernatural red ox, dramatic market chaos atmosphere, no text, no watermark",
    tags: ["东山经", "牛", "赤色"],
    bagua: "li",
  },
];

// 中山经异兽
const ZHONGSHAN_CREATURES: Creature[] = [
  {
    id: "dou",
    name: "脰",
    source: "《山海经·中山经》",
    rawText: "脱扈之山，有兽焉，其状如犬而有角，其名曰脰。",
    promptZh: "生成一张山海经脰异兽插图，狗形却头生独角的异兽在中山的荒草中独行，独角在月光下泛着冷光，狗的身形透着机警，耳朵竖起警觉地巡视四周，中国上古独角异兽。",
    promptEn: "A mysterious Chinese single-horned beast Dou, Shan Hai Jing illustration, dog-like creature with a single horn on its head, wandering through the desolate grasses of Zhongshan mountain, horn glowing with cold light under moonlight, alert dog-like form with pricked ears scanning surroundings, ancient Chinese single-horned creature, dark atmospheric tones, no text, no watermark",
    tags: ["中山经", "犬", "独角"],
    bagua: "gen",
  },
  {
    id: "qi-zhong",
    name: "跂踵",
    source: "《山海经·中山经》",
    rawText: "倚帝之山，有兽焉，其状如鼔鼠而有角，其名曰跂踵。",
    promptZh: "生成一张山海经跂踵插图，人面却长着鼔鼠身体和猪蹄的奇异生物，在倚帝山的乱石间缓慢移动，人面透着呆滞而诡异的神情，猪蹄在岩石上踏出沉闷的声音，中国上古人面异兽。",
    promptEn: "A grotesque Chinese beast Qi Zhong, Shan Hai Jing illustration, humanoid face with鼔鼠-like body and pig hooves, slowly moving through rocky Zhongshan mountain terrain, dull eerie human expression, pig hooves clattering on stones making dull sounds, ancient Chinese strange creature, grim rocky atmosphere, no text, no watermark",
    tags: ["中山经", "人面", "猪蹄"],
    bagua: "xun",
  },
  {
    id: "lun-lun",
    name: "轮轮",
    source: "《山海经·中山经》",
    rawText: "倚帝之山，有虫焉，其状如鼔虫而有角，其名曰轮轮。",
    promptZh: "生成一张山海经轮轮异虫插图，巨大昆虫形态却头生多角的奇异生物在倚帝山的腐叶间爬行，节肢闪烁着油亮光泽，人面般的头部透着诡异，触角在潮湿的林地空气中颤动，中国上古异虫。",
    promptEn: "A monstrous Chinese insect Lun Lun, Shan Hai Jing illustration, giant insect creature with multiple horns on human-like head, crawling through fallen leaves on Zhongshan mountain, glossy segmented body glistening, eerie humanoid head expression, antennae trembling in damp forest air, ancient Chinese strange arthropod, dark earthy atmosphere, no text, no watermark",
    tags: ["中山经", "虫", "人面虫"],
    bagua: "gen",
  },
  {
    id: "hua-she",
    name: "化蛇",
    source: "《山海经·中山经》",
    rawText: "阳华山之山，有蛇焉，名曰化蛇，其状如人面而豺身，鸟翼而蛇行，其音如叱呼，见则其邑大水。",
    promptZh: "生成一张山海经化蛇插图，人面豺身鸟翼的恐怖异蛇在暴雨来临前的阳华山中滑行，豺身肌肉紧绷，人面透着狰狞，巨翼在风暴前夕卷起狂风，周围是大雨即将倾盆的压抑天空，中国上古兆水灾凶蛇。",
    promptEn: "A terrifying flood-omen Chinese serpent Hua She, Shan Hai Jing illustration, humanoid-faced creature with jackal body and bird wings sliding through Yanghua mountain before storm, muscular jackal body,狰狞 human face, enormous wings creating gale winds before deluge, oppressive sky of imminent heavy rain, ancient Chinese water disaster omen, dramatic storm atmosphere, no text, no watermark",
    tags: ["中山经", "蛇", "兆水灾"],
    bagua: "li",
  },
  {
    id: "fu-zhu",
    name: "夫诸",
    source: "《山海经·中山经》",
    rawText: "女几之山，有兽焉，其状如白鹿而四角，见则其国大水。",
    promptZh: "生成一张山海经夫诸插图，通体雪白的四角神鹿站在即将爆发洪水的城邑郊外，四只角如水晶般通透泛光，天空乌云压顶，城郭在远处已被洪水包围，白鹿眼含哀伤望着城中的灯火，中国上古兆水灾瑞兽。",
    promptEn: "A beautiful flood-omen Chinese white stag Fu Zhu, Shan Hai Jing illustration, pure white deer with four crystal-like translucent antlers standing outside a flood-threatened city, dark clouds pressing down overhead, city walls already surrounded by flood waters in distance, white deer gazing sadly at city lights below, ancient Chinese water disaster omen, dramatic atmospheric tension, no text, no watermark",
    tags: ["中山经", "鹿", "兆水灾"],
    bagua: "kan",
  },
  {
    id: "san-zu-gui",
    name: "三足龟",
    source: "《山海经·中山经》",
    rawText: "灵龟之山，有三足龟。",
    promptZh: "生成一张山海经三足龟插图，通体青绿色的神龟只有三只脚，第三只脚稳健地支撑着龟壳，三足在清澈的灵龟山泉中涉水前行，龟壳上布满神秘的符文，泉水在足下泛起金色涟漪，中国上古三足神龟。",
    promptEn: "A divine three-legged Chinese turtle San Zu Gui, Shan Hai Jing illustration, turquoise turtle with only three legs, third leg solidly supporting the shell, wading through crystal clear spirit spring of Linggui mountain, mysterious ancient symbols carved on shell, golden ripples beneath the feet, ancient Chinese three-legged sacred turtle, serene spring atmosphere, no text, no watermark",
    tags: ["中山经", "龟", "三足"],
    bagua: "zhen",
  },
];

// 大荒经异兽
const DAHUANG_CREATURES: Creature[] = [
  {
    id: "kui-niu",
    name: "夔牛",
    source: "《山海经·大荒东经》",
    rawText: "东海中有流波山，入海七千里。其上有兽，状如牛，苍身而无角，一足，出入水则必有风雨，其光如日月，其声如雷，其名曰夔。黄帝得之，以其皮为鼓，橛以雷兽之骨，声闻五百里，以威天下。",
    promptZh: "生成一张山海经夔牛插图，独脚青灰色神牛站在雷雨交加的东海之中，雷电交加的氛围，独脚站立的姿态，单眼如烈日般炽烈燃烧，周身风雨大作，青铜器纹饰风格，远景海浪翻涌，肃穆而震撼的中国神话氛围",
    promptEn: "A mythical Chinese beast Kui Niu, ancient bronze ritual vessel art style, single-legged blue-grey bull standing in a thunderstorm sea, its body glowing like moonlight, lightning and rain surrounding it, one cyclopean eye blazing like the sun, dramatic silhouette, dark stormy ocean backdrop, ancient Chinese mythological creature, bronze mask aesthetic, visceral powerful presence, no text, no watermark",
    tags: ["大荒东经", "神兽", "雷兽"],
    bagua: "gen",
  },
  {
    id: "ying-long",
    name: "应龙",
    source: "《山海经·大荒东经》",
    rawText: "应龙处南极，杀蚩尤与夸父，不得复上。故下数旱，旱而为应龙之状，乃得大雨。",
    promptZh: "生成一张山海经应龙插图，金色神龙展开巨大双翅斩杀魔神，蚩尤与夸父败退于脚下，风云变色，电闪雷鸣，天界与凡间交汇之处，应龙身上散发金色光芒与雷霆之力，中国上古战争神话场景。",
    promptEn: "A divine Chinese dragon Ying Long, ancient Shan Hai Jing illustration, golden divine dragon with enormous spread wings battling Chi You and Kua Fu, lightning and storm surrounding the scene, divine golden light emanating from the dragon, mythological war scene between gods and giants, dramatic Wu Xia cinematic atmosphere, dark thunder clouds with golden divine rays, powerful heroic pose, Chinese mythological art, no text, no watermark",
    tags: ["大荒东经", "神龙", "战神"],
    bagua: "zhen",
  },
  {
    id: "she-bi",
    name: "奢比",
    source: "《山海经·大荒东经》",
    rawText: "大荒东有神人面犬耳，珥两青蛇，名曰奢比。",
    promptZh: "生成一张山海经奢比尸神插图，人面犬耳的神灵耳朵上挂着两条游动的青蛇，在云雾缭绕的大荒之野驻足，青蛇吐信，犬耳耸立，中国上古荒野神灵。",
    promptEn: "A divine Chinese spirit She Bi, Shan Hai Jing illustration, deity with human face and dog ears wearing two living green snakes on each ear, standing in misty wilderness of the Great Wasteland, snakes flickering tongues, dog ears perked up alert, ancient Chinese wilderness deity, mysterious fog atmosphere, no text, no watermark",
    tags: ["大荒东经", "神祇", "荒野"],
    bagua: "xun",
  },
  {
    id: "zhu-long",
    name: "烛龙",
    source: "《山海经·大荒北经》",
    rawText: "西北海之外，赤水之北，有章尾山。有神，人面蛇身而赤，直目正乘，其瞑乃晦，其视乃明，不食不寝不息，风雨是谒。是烛九阴，是烛龙。",
    promptZh: "生成一张山海经烛龙插图，巨大的红色人面蛇身神占据画面中央，烛龙的眼睛睁闭之间控制昼夜交替，通体散发着日月般的光芒，周围风雨环绕，背景是幽暗神秘的山海世界，水墨古风，武侠电影般的史诗氛围。",
    promptEn: "A legendary Chinese fire deity Zhu Long, ancient ink wash painting style, a massive red humanoid face atop an enormous serpent body stretching across the landscape, eyes closed for night and open for day, glowing like the sun and moon, surrounded by swirling mist and wind, dramatic Wu Xia cinematic atmosphere, dark mystical background with red and gold accents, intricate scales, powerful divine presence, Chinese mythological art, detailed texture, no text, no watermark",
    tags: ["大荒北经", "神祇", "昼夜"],
    bagua: "kan",
  },
  {
    id: "kua-fu",
    name: "夸父",
    source: "《山海经·大荒北经》",
    rawText: "夸父与日逐走，入日，渴欲得饮。饮于河渭，河渭不足，北饮大泽。未至，道渴而死。弃其杖，化为邓林。",
    promptZh: "生成一张山海经夸父逐日插图，巨人夸父在夕阳下狂奔追赶太阳，黄河渭河的水被他一饮而尽，巨大的身躯在山峦间奔跑，手杖化为桃林在身后盛开，中国上古悲剧英雄神话。",
    promptEn: "A giant Chinese hero Kua Fu chasing the sun, Shan Hai Jing illustration, colossal figure running across mountains chasing the setting sun, drinking the Yellow River and Wei River in massive gulps, body casting enormous shadow, walking stick transforming into blossoming peach grove behind, ancient Chinese tragic hero myth, warm sunset dramatic atmosphere, no text, no watermark",
    tags: ["大荒北经", "巨人", "逐日"],
    bagua: "gen",
  },
  {
    id: "xiang-liu",
    name: "相柳",
    source: "《山海经·大荒北经》",
    rawText: "共工臣名曰相繇，九首蛇身，自环食于九土。",
    promptZh: "生成一张山海经相柳插图，九个人面巨蛇身的恐怖凶神盘踞在中原大地，九个人面表情各异，九个脑袋同时吞噬万物，所到之处化为沼泽毒池，九张嘴同时喷出黑色的污秽之物，中国上古水神恶臣。",
    promptEn: "A terrifying nine-headed Chinese monster Xiang Liu, Shan Hai Jing illustration, nine human-faced serpent bodies coiling across the central plains, nine heads devouring everything simultaneously, wherever it goes turning into poisonous swamps, nine mouths spitting black filth together, ancient Chinese water god's evil minister, dark grim atmosphere, no text, no watermark",
    tags: ["大荒北经", "凶兽", "水神"],
    bagua: "qian",
  },
  {
    id: "chi-you",
    name: "蚩尤",
    source: "《山海经·大荒北经》",
    rawText: "蚩尤作兵伐黄帝，黄帝乃令应龙攻之冀州之野。",
    promptZh: "生成一张山海经蚩尤战神插图，武冠华服的巨人战神蚩尤站在战场中央，手持巨大的战戈和战盾，身后是铜头铁额的八十一位兄弟，脚下是被击败的敌人，中国上古战争之神。",
    promptEn: "Chinese war god Chi You, Shan Hai Jing illustration, battle-crowned warrior giant standing at center of battlefield, holding massive halberd and shield, eighty-one copper-headed brothers behind, defeated enemies at feet, ancient Chinese god of war, bloody battlefield atmosphere, dramatic war scene, no text, no watermark",
    tags: ["大荒北经", "神祇", "战神"],
    bagua: "qian",
  },
  {
    id: "jiu-feng",
    name: "九凤",
    source: "《山海经·大荒北经》",
    rawText: "大荒之中，有神，九首人面鸟身，名曰九凤。",
    promptZh: "生成一张山海经九凤插图，九个人面的神凤展开巨大的九翼在九天之上翱翔，羽色五彩祥瑞，每个凤头神态各异——有吟唱有长鸣有低语，九道神光从翅膀散开，中国上古九头神凤。",
    promptEn: "A divine nine-headed Chinese phoenix Jiu Feng, Shan Hai Jing illustration, nine human-faced divine phoenixes spreading nine enormous wings across the heavens, five-colored iridescent plumage, each phoenix head with different expression—some singing, some crying, some whispering, nine divine light rays radiating from wings, ancient Chinese nine-headed sacred bird, celestial grand atmosphere, no text, no watermark",
    tags: ["大荒北经", "神鸟", "九头"],
    bagua: "li",
  },
  {
    id: "chang-xi",
    name: "嫦娥",
    source: "《山海经·大荒西经》",
    rawText: "帝俊妻常羲，浴月，取月精。",
    promptZh: "生成一张山海经常羲（嫦娥）插图，月中女神在银色的月宫中沐浴，月光如水银般倾泻，玉兔捣药于旁，桂树飘香，中国上古月神形象，水墨银蓝月光色调。",
    promptEn: "Chinese moon goddess Chang Xi, Shan Hai Jing illustration, divine woman bathing in silver moon palace, moonlight pouring like liquid silver, jade rabbit grinding elixir beside her, cassia tree fragrance filling the air, ancient Chinese moon deity, silver-blue moonlit palette, ethereal serene atmosphere, no text, no watermark",
    tags: ["大荒西经", "神祇", "月神"],
    bagua: "dui",
  },
  {
    id: "xi-wang-mu",
    name: "西王母",
    source: "《山海经·大荒西经》",
    rawText: "玉山，是西王母所居也。西王母其状如人，豹尾虎齿而善啸，蓬发戴胜。",
    promptZh: "生成一张山海经西王母插图，豹尾虎齿的威严女神戴玉胜披长发端坐于昆仑瑶池旁，虎齿微露却不失慈祥，身边有三青鸟侍奉，瑶草琪花盛开，中国上古女神之祖。",
    promptEn: "Queen Mother of the West Xi Wang Mu, Shan Hai Jing illustration, majestic goddess with leopard tail and tiger fangs wearing jade crown, long disheveled hair, seated beside Kunlun Yaochi pool, slight fangs yet benevolent expression, three blue birds serving her, celestial flowers blooming around, ancient Chinese supreme goddess, grand celestial atmosphere, no text, no watermark",
    tags: ["大荒西经", "神祇", "女神"],
    bagua: "kun",
  },
  {
    id: "bu-si-min",
    name: "不死民",
    source: "《山海经·大荒南经》",
    rawText: "有不死民，不死者皆面黄。",
    promptZh: "生成一张山海经不死民插图，面色金黄的不死之民在南方炎热之地劳作，房屋被奇花异草环绕，远处的灵泉泛着不死之光，周围是永不枯竭的果实，中国上古不死之民的祥和画面。",
    promptEn: "An immortal Chinese person Bu Si Min, Shan Hai Jing illustration, golden-faced immortal beings working in southern lands of eternal warmth, homes surrounded by exotic flowers and herbs, fountain of immortality glowing nearby, inexhaustible fruit trees around, serene ancient Chinese immortality scene, warm golden atmosphere, no text, no watermark",
    tags: ["大荒南经", "异人", "不死"],
    bagua: "li",
  },
  {
    id: "yu-she",
    name: "育蛇",
    source: "《山海经·大荒南经》",
    rawText: "南方有育蛇，风生兽。",
    promptZh: "生成一张山海经育蛇插图，神蛇在南方丛林中盘踞，鳞片泛着温润的绿光，守护着身后的不死之树，树上有永不凋谢的花朵，中国上古南方守护神蛇。",
    promptEn: "A divine southern Chinese serpent Yu She, Shan Hai Jing illustration, sacred serpent coiling in southern jungle, warm green scales glistening, guarding an immortal tree behind with never-wilting flowers, ancient Chinese southern guardian serpent, lush jungle atmosphere, no text, no watermark",
    tags: ["大荒南经", "蛇", "南方"],
    bagua: "xun",
  },
  {
    id: "ling-shan-shi-wu",
    name: "灵山十巫",
    source: "《山海经·大荒西经》",
    rawText: "灵山有十巫，咸皆升降，百药爰在。",
    promptZh: "生成一张山海经灵山十巫插图，十位巫师在灵山之巅进行祭祀仪式，各执法器，灵草仙药满山遍野，神光笼罩，与天地沟通的神秘场景，中国上古巫术文化。",
    promptEn: "Ten Chinese wizards on sacred Ling Shan mountain, Shan Hai Jing illustration, ten shamans performing ritual at the mountain summit, each holding mystical implements, divine healing herbs covering the slopes, sacred light enveloping the scene, ancient Chinese shamanic culture, misty mountain atmosphere, no text, no watermark",
    tags: ["大荒西经", "神祇", "巫术"],
    bagua: "gen",
  },
  {
    id: "qi-chong",
    name: "齐虫",
    source: "《山海经·大荒北经》",
    rawText: "北方有禹虫，强不可听。",
    promptZh: "生成一张山海经齐虫插图，巨大的虫形生物在北方寒冷荒野中蠕动，身体庞大到遮蔽天日，发出人耳无法承受的低频轰鸣，北方大荒的苍茫背景，中国上古恐怖巨虫。",
    promptEn: "A monstrous insect deity Qi Chong, Shan Hai Jing illustration, enormous worm-like creature writhing in the cold northern wilderness, body so massive it blocks out the sun, emitting low-frequency droning sound that human ears cannot bear, desolate northern great wasteland backdrop, ancient Chinese terrifying mega insect, grim atmospheric tones, no text, no watermark",
    tags: ["大荒北经", "虫", "北方"],
    bagua: "kan",
  },
];

// 海外经异兽
const HAIWAI_CREATURES: Creature[] = [
  {
    id: "bi-fang",
    name: "毕方",
    source: "《山海经·海外南经》",
    rawText: "毕方鸟在其东，青水西，其为鸟人面一脚。",
    promptZh: "生成一张山海经毕方插图，独足白喙仙鹤立于枯木之巅，羽毛黑色带赤红火焰纹路，羽尖燃着微火，周围赤地千里，远处天际如烧，独脚抬起，单足站立于枯槁老树，水墨写意与工笔结合的中国神话意境。",
    promptEn: "A solitary mystical bird Bi Fang, Shan Hai Jing ancient illustration, elegant crane-like creature with pure white beak and black feathers with crimson flame patterns across its wings, standing alone on a withered ancient tree in a dry landscape, single leg raised, small flame burning at its feather tips, fire omen bird, Chinese ink wash painting, barren mountains, no text, no watermark",
    tags: ["海外南经", "鸟", "兆火"],
    bagua: "li",
  },
  {
    id: "guan-guan",
    name: "灌灌",
    source: "《山海经·海外南经》",
    rawText: "青丘之山，有鸟焉，其状如鸠，其音若呵，名曰灌灌，佩之不惑。",
    promptZh: "生成一张山海经灌灌插图，斑鸠外形却通体青色，在青丘山的云雾中成群飞翔，鸣叫声响彻山谷，羽色在晨光中泛着神秘光泽，中国上古佩之不惑的灵鸟。",
    promptEn: "A mystical Chinese bird Guan Guan, Shan Hai Jing illustration, dove-like blue-green bird flying in misty Qingqiu mountains, calls echoing through the valley, feathers glowing with mysterious sheen in morning light, ancient Chinese clarifying spirit bird, ethereal misty atmosphere, no text, no watermark",
    tags: ["海外南经", "鸟", "佩之不惑"],
    bagua: "xun",
  },
  {
    id: "bi-feng",
    name: "比翼鸟",
    source: "《山海经·海外南经》",
    rawText: "比翼之鸟，其状如凫，一翼一目，相得乃飞。",
    promptZh: "生成一张山海经比翼鸟插图，两只各只有一只翅膀一只眼睛的鸟紧紧相依，在海天之间的云霞中共同飞翔，翅膀配合得天衣无缝，五彩祥云环绕，中国上古相依相助的神鸟。",
    promptEn: "A pair of Chinese Bifeng birds, Shan Hai Jing illustration, two birds each with only one wing and one eye, embracing tightly while flying through rosy clouds between sea and sky, wings perfectly coordinated, colorful auspicious clouds surrounding, ancient Chinese interdependent spirit birds, romantic ethereal atmosphere, no text, no watermark",
    tags: ["海外南经", "鸟", "相依"],
    bagua: "li",
  },
  {
    id: "ka-ming",
    name: "开明兽",
    source: "《山海经·海外西经》",
    rawText: "昆仑之墟方八百里，高万仞……有九门，门有开明兽守之……开明兽身大类虎，而九首皆人面，东向立昆仑上。",
    promptZh: "生成一张山海经开明兽插图，如白虎般巨大的神兽躯体上生着九颗人面，九张面孔神态各异皆警觉巡视，九尾横扫身后，守护昆仑天宫九门，金白神光环绕，远景昆仑仙境，武侠电影分镜般的史诗构图。",
    promptEn: "A fearsome Chinese guardian beast Ka Ming, Shan Hai Jing illustration, colossal white tiger-like body with nine human-faced heads emerging, each face with a different expression of vigilance, nine tails sweeping behind, guarding the entrance to a golden celestial palace, mountain peak backdrop, divine white glow with golden light, majestic and terrifying, Chinese mythological art, no text, no watermark",
    tags: ["海外西经", "神兽", "昆仑"],
    bagua: "kun",
  },
  {
    id: "cheng-huang",
    name: "乘黄",
    source: "《山海经·海外西经》",
    rawText: "白民之国在龙鱼北，白身披发。有乘黄，其状如狐，其背角，乘之寿二千岁。",
    promptZh: "生成一张山海经乘黄插图，如狐狸般的金色神兽，背生独角，展开由光芒构成的巨大双翼，飞行于远古神话疆域之上，骑者剪影在其背上，天界金色光芒笼罩，中国神话中的长生祥瑞之兽。",
    promptEn: "A legendary Chinese flying beast Cheng Huang, ancient Shan Hai Jing painting, fox-like creature covered in golden-yellow fur with a single horn on its back, spreading enormous translucent wings made of light, flying above ancient mythical landscape, rider silhouette on its back, celestial golden glow, immortality symbol, Chinese mythological art, no text, no watermark",
    tags: ["海外西经", "神兽", "长寿"],
    bagua: "dui",
  },
  {
    id: "long-yu",
    name: "龙鱼",
    source: "《山海经·海外西经》",
    rawText: "豪鱼出运作，状如鲤鱼。",
    promptZh: "生成一张山海经龙鱼插图，巨大如鲤鱼的龙鱼在海外仙境的清澈池中游弋，鳞片泛着金色光芒，须龙般的长须飘动，周围是仙山楼阁，中国上古龙鱼形象。",
    promptEn: "A divine Chinese dragon fish Long Yu, Shan Hai Jing illustration, giant carp-like dragon fish swimming in a crystal pond of an overseas fairyland, golden scales glowing, dragon-like whiskers flowing, surrounded by fairy mountains and pavilions, ancient Chinese imperial dragon fish, celestial atmosphere, no text, no watermark",
    tags: ["海外西经", "水族", "龙"],
    bagua: "kan",
  },
  {
    id: "zou-yu",
    name: "驺虞",
    source: "《山海经·海外北经》",
    rawText: "驺虞，白虎黑尾，义兽也，不践生草，食自死之肉。",
    promptZh: "生成一张山海经驺虞插图，白虎身形却有一条飘逸的黑尾，在雪山草原间优雅漫步，仁慈安详的神态，不杀生的慈悲之兽，周围是祥和的瑞草和甘泉，中国上古仁义之兽。",
    promptEn: "A benevolent Chinese divine beast Zou Yu, Shan Hai Jing illustration, white tiger-like creature with a flowing black tail, walking gracefully through snowy grasslands, serene and peaceful expression, compassionate creature that never kills living beings, auspicious herbs and crystal spring around, ancient Chinese benevolent mythical animal, no text, no watermark",
    tags: ["海外北经", "神兽", "仁义"],
    bagua: "gen",
  },
  {
    id: "man-man",
    name: "蛮蛮",
    source: "《山海经·大荒南经》",
    rawText: "崇吾之山，有鸟焉，其状如凫，而一翼一目，相得乃飞，名曰蛮蛮，见则天下大水。",
    promptZh: "生成一张山海经蛮蛮异鸟插图，两只各只有一只翅膀一只眼睛的鸟，必须紧紧相依才能飞翔，于暴风雨前的湖面之上，狂风卷起巨浪，却无法将它们分开，中国神话中的"相得乃飞"意象。",
    promptEn: "A pair of mythical birds Man Man, Shan Hai Jing ancient illustration, two birds each with only one wing and one eye, embracing each other tightly while flying through a stormy lake surface, gale winds creating massive waves yet unable to separate them, the moment before a great flood, Chinese mythological symbol of interdependence, no text, no watermark",
    tags: ["大荒南经", "鸟", "相依"],
    bagua: "li",
  },
];

// 海内经异兽
const HAINEI_CREATURES: Creature[] = [
  {
    id: "dou-yu",
    name: "窦窳",
    source: "《山海经·海内南经》",
    rawText: "窦窳，龙首，居龟水中，西食人。",
    promptZh: "生成一张山海经窦窳插图，龙头异兽从幽暗水穴中探出，龙头人身或龙头兽身的恐怖形态，利爪抓紧岩石，波涛汹涌的水面，从西方逼近古代部落，中国上古食人水怪。",
    promptEn: "A terrifying Chinese monster Dou Yu, Shan Hai Jing illustration, dragon-headed beast emerging from a dark watery cave, horrifying form with dragon head on human or beast body, claws gripping rocks, turbulent waves surging around, approaching ancient tribes from the west, ancient Chinese man-eating water monster, dramatic dark atmosphere, no text, no watermark",
    tags: ["海内南经", "凶兽", "食人"],
    bagua: "kan",
  },
  {
    id: "xing-xing",
    name: "猩猩",
    source: "《山海经·海内经》",
    rawText: "猩猩知人名，其状如狌狌，而人与兽。",
    promptZh: "生成一张山海经猩猩插图，上古猩猩人面兽身在热带丛林中与人相遇，知道人的姓名却故意装作不知道，聪明的眼神透着狡黠，旁有人类猎手设下陷阱，中国上古智兽。",
    promptEn: "An intelligent Chinese ape Xing Xing, Shan Hai Jing illustration, ape-like creature with humanoid face knowing human names, deliberately pretending not to recognize hunters' names while watching them set traps, cunning intelligent gaze, ancient subtropical jungle setting, ancient Chinese wise beast, dramatic jungle atmosphere, no text, no watermark",
    tags: ["海内经", "异兽", "智兽"],
    bagua: "xun",
  },
];

// 附录专题异兽
const TOPIC_CREATURES: Creature[] = [
  // 四大凶兽
  {
    id: "hun-dun",
    name: "混沌",
    source: "《山海经》延伸记载 +《神异经》",
    rawText: "混沌，外表像犬，四足无爪，有目而不见，行走不便，有翅膀，欺负善良，喜欢残暴的人。所以称是非不分的人为"混沌"。",
    promptZh: "生成一张混沌异兽插图，形状像狗但无定形，浑身散发着虚无的灰白色光芒，有眼却看不见，有耳却听不见，蜷伏在黑暗的虚空中，旁边是善恶两个对比形象，中国神话中的混沌意象，上古凶兽氛围。",
    promptEn: "A primordial Chinese chaos entity Hun Dun, Shan Hai Jing ancient illustration, formless creature resembling a shapeless dog-like mass, glowing faintly with grey-white ethereal light, eyes open but blind, ears present but deaf, curled in void darkness, side view showing moral contrast between good and evil, ancient Chinese mythological atmosphere, ink wash painting style, no text, no watermark",
    tags: ["四凶", "混沌", "虚无意象"],
    bagua: "kan",
  },
  {
    id: "tao-wu",
    name: "梼杌",
    source: "《左传》/《山海经》延伸",
    rawText: "梼杌，形状像虎而犬毛，长二尺，人面，虎足，猪口牙，尾长一丈八尺，搅乱荒中。",
    promptZh: "生成一张梼杌插图，人面虎足却拥有野猪的獠牙和犬类的皮毛，尾巴长达数米横扫荒野，凶残的表情凝固在愤怒中，黄土高原般的苍凉背景，中国上古凶兽图腾风格。",
    promptEn: "A ferocious Chinese mythical beast Tao Wu, Shan Hai Jing ancient style, creature with human-like face on a tiger-leopard body, boar tusks protruding from a canine mouth, very long tail sweeping the desolate landscape, fierce angry frozen expression, barren earth-toned background, ancient Chinese mythological凶兽 aesthetic, no text, no watermark",
    tags: ["四凶", "梼杌", "顽固"],
    bagua: "qian",
  },
  {
    id: "tao-tie",
    name: "饕餮",
    source: "《山海经·北山经》狍鸮/《神异经》",
    rawText: "饕餮，兽名，身多毛，性好食，多贪婪。",
    promptZh: "生成一张饕餮插图，羊身人面的凶兽融合怪物，眼睛在腋下，虎齿狰狞外露，青铜饕餮纹覆满全身，站在堆积如山的食物和宝物前，贪婪地张开大嘴，周围是已被吃空的残骸，中国上古贪食凶兽。",
    promptEn: "A gluttonous Chinese beast Taotie, ancient bronze ware style, grotesque fusion of human face on goat body, eyes in armpits, exposed tiger fangs, standing before a mountain of food and treasures with mouth wide open in greed, surroundings showing empty remnants of devoured feasts, ancient Chinese gluttonous mythological creature, dark obsessive atmosphere, no text, no watermark",
    tags: ["四凶", "饕餮", "贪食"],
    bagua: "dui",
  },
  // 龙生九子
  {
    id: "qiu-niu",
    name: "囚牛",
    source: "《升庵外集》",
    rawText: "囚牛，龙种，性好音。",
    promptZh: "生成一张囚牛龙子插图，龙首牛身的优雅神灵蹲坐在古琴之上，耳朵专注地聆听琴弦的振动，身边环绕着音符和雅乐，远处是古代宫廷的音乐厅，中国乐神形象。",
    promptEn: "A musical Chinese dragon son Qiu Niu, Shan Hai Jing illustration, dragon-headed ox-bodied deity perched gracefully atop an ancient guqin zither, ears attentive to vibrating strings, musical notes floating around, ancient palace music hall in distance, Chinese music deity aesthetic, serene elegant atmosphere, no text, no watermark",
    tags: ["龙子", "囚牛", "音乐"],
    bagua: "li",
  },
  {
    id: "ya-zi",
    name: "睚眦",
    source: "《升庵外集》",
    rawText: "睚眦，龙种，性好杀。",
    promptZh: "生成一张睚眦龙子插图，龙首豺身的威严神灵身挂战刀，刀柄上盘着睚眦的造像，龙嘴微张露出獠牙，怒目圆睁，中国古代战神形象。",
    promptEn: "A fierce Chinese dragon son Ya Zi, Shan Hai Jing illustration, dragon-headed wolf-bodied deity wearing a battle sword, Ya Zi coiled on sword handle, dragon mouth slightly open revealing fangs, eyes wide with rage, ancient Chinese war god aesthetic, dark dramatic atmosphere, no text, no watermark",
    tags: ["龙子", "睚眦", "嗜杀"],
    bagua: "zhen",
  },
  {
    id: "pu-lao",
    name: "蒲牢",
    source: "《升庵外集》",
    rawText: "蒲牢，龙种，性好鸣。",
    promptZh: "生成一张蒲牢龙子插图，盘踞在古钟顶端的龙子，钟身上铸着蒲牢的形象，龙口大开正在吼叫，声音化为可见的声波扩散，中国古代钟鼓之龙。",
    promptEn: "A vocal Chinese dragon son Pu Lao, Shan Hai Jing illustration, dragon coiled atop ancient temple bell, Pu Lao casting on bell surface, dragon mouth wide open roaring, sound waves visualized as rippling rings spreading outward, ancient Chinese bell dragon aesthetic, dramatic resonant atmosphere, no text, no watermark",
    tags: ["龙子", "蒲牢", "好鸣"],
    bagua: "kan",
  },
  {
    id: "suan-ni",
    name: "狻猊",
    source: "《升庵外集》",
    rawText: "狻猊，龙种，似狮子，性好烟火。",
    promptZh: "生成一张狻猊龙子插图，狮子外形的龙子端坐在佛前的香炉旁，烟雾缭绕，龙鬃在烟中若隐若现，威严而安详，中国佛教护法神兽。",
    promptEn: "A Buddhist Chinese dragon son Suan Ni, Shan Hai Jing illustration, lion-like dragon offspring sitting beside a Buddhist incense burner, smoke curling around, dragon mane visible through the mist, dignified yet peaceful expression, Chinese Buddhist guardian aesthetic, serene incense-filled atmosphere, no text, no watermark",
    tags: ["龙子", "狻猊", "烟火"],
    bagua: "gen",
  },
  {
    id: "ba-xia",
    name: "霸下",
    source: "《升庵外集》",
    rawText: "霸下，龙种，似龟，性好负重。",
    promptZh: "生成一张霸下龙子插图，龟形龙子背负着巨大的石碑艰难前行，石碑上刻着上古的历史和神迹，汗水从龟壳边缘滴落，中国古代负重神兽。",
    promptEn: "A steadfast Chinese dragon son Ba Xia, Shan Hai Jing illustration, turtle-like dragon offspring struggling forward carrying an enormous stone tablet, ancient histories and divine records carved on the tablet, sweat dripping from beneath the shell, Chinese ancient beast carrying duty, determined atmosphere, no text, no watermark",
    tags: ["龙子", "霸下", "负重"],
    bagua: "kun",
  },
  {
    id: "bi-an",
    name: "狴犴",
    source: "《升庵外集》",
    rawText: "狴犴，龙种，似虎，性好讼。",
    promptZh: "生成一张狴犴龙子插图，虎形龙子庄严地端坐在古代官衙的大堂之上，肃穆的官服和惊堂木在旁边，龙睛炯炯有神维护公堂正义，中国古代法律守护神。",
    promptEn: "A righteous Chinese dragon son Bi An, Shan Hai Jing illustration, tiger-like dragon offspring solemnly seated in ancient court of justice, official robes and judicial hammer beside, dragon eyes bright with justice, maintaining order in the public hall, Chinese ancient legal guardian, solemn dignified atmosphere, no text, no watermark",
    tags: ["龙子", "狴犴", "好讼"],
    bagua: "li",
  },
  {
    id: "fu-xi",
    name: "负屃",
    source: "《升庵外集》",
    rawText: "负屃，龙种，似龙形，性好文。",
    promptZh: "生成一张负屃龙子插图，龙形神灵盘绕在石碑顶端，石碑上刻满了古老的诗文和铭文，龙头低垂欣赏碑文，儒雅的中国书卷之龙。",
    promptEn: "A literary Chinese dragon son Fu Xi, Shan Hai Jing illustration, dragon-like deity coiling atop ancient stone tablet, classical poems and inscriptions carved on the surface, dragon head bowed in appreciation of the writings, scholarly Chinese literary dragon, elegant refined atmosphere, no text, no watermark",
    tags: ["龙子", "负屃", "喜文"],
    bagua: "xun",
  },
  {
    id: "chi-wen",
    name: "螭吻",
    source: "《升庵外集》",
    rawText: "螭吻，龙种，鱼身，性好吞。",
    promptZh: "生成一张螭吻龙子插图，鱼形龙子盘踞在古代宫殿的屋脊之上，张开大嘴吞食着屋脊尽头的雨水，火焰从龙鳞间微微透出，建筑脊兽之首，中国古代屋檐守护神。",
    promptEn: "A Chinese dragon son Chi Wen, Shan Hai Jing illustration, fish-shaped dragon perched atop ancient palace roof ridge, mouth wide open swallowing rainwater from the eave tips, faint flames visible through scales, premier architectural ridge guardian, Chinese ancient rooftop protector, dramatic rainstorm atmosphere, no text, no watermark",
    tags: ["龙子", "螭吻", "好吞"],
    bagua: "dui",
  },
  // 四灵/四神
  {
    id: "qing-long",
    name: "青龙",
    source: "《山海经》/《淮南子》",
    rawText: "青龙，天之四灵之一，东方之灵。",
    promptZh: "生成一张山海经青龙插图，巨大的青色神龙在东海之滨腾云驾雾，龙须飘荡如流云，青色鳞片在晨曦中泛着万道光芒，龙爪张开守护东方，中国四灵之首。",
    promptEn: "A divine Chinese Azure Dragon Qing Long, Shan Hai Jing illustration, enormous blue-green dragon rising above the eastern sea through clouds, dragon whiskers flowing like streams, blue-green scales glistening with ten thousand rays of dawn light, claws outstretched protecting the east, premier of the Four Celestial Guardians, dramatic sunrise atmosphere, no text, no watermark",
    tags: ["四灵", "青龙", "东方"],
    bagua: "gen",
  },
  {
    id: "bai-hu",
    name: "白虎",
    source: "《山海经》/《淮南子》",
    rawText: "白虎，天之四灵之一，西方之灵。",
    promptZh: "生成一张山海经白虎插图，威严的白虎神兽伫立于西山之巅，白色皮毛在夕阳下泛着金光，虎纹如墨渲染，肃杀之气弥漫，中国四灵之虎。",
    promptEn: "A majestic Chinese White Tiger Bai Hu, Shan Hai Jing illustration, dignified white tiger standing atop western mountain summit, pure white fur glowing golden under sunset, tiger stripes like ink wash painting, solemn deadly aura filling the air, one of the Four Celestial Guardians, dramatic western sunset atmosphere, no text, no watermark",
    tags: ["四灵", "白虎", "西方"],
    bagua: "qian",
  },
  {
    id: "zhu-que",
    name: "朱雀",
    source: "《山海经》/《淮南子》",
    rawText: "朱雀，天之四灵之一，南方之灵。",
    promptZh: "生成一张山海经朱雀神鸟插图，烈火般的红雀展开双翼在南方火山之上盘旋，羽毛如燃烧的火焰，眼眸如烈日，鸣叫声化为火焰从天而降，中国四灵之朱雀。",
    promptEn: "A divine Chinese Vermilion Bird Zhu Que, Shan Hai Jing illustration, crimson phoenix spreading wings above southern volcanoes, feathers like burning flames, eyes like scorching sun, cries turning into flames falling from heaven, one of the Four Celestial Guardians, dramatic volcanic atmosphere, no text, no watermark",
    tags: ["四灵", "朱雀", "南方"],
    bagua: "li",
  },
  {
    id: "xuan-wu",
    name: "玄武",
    source: "《山海经》/《淮南子》",
    rawText: "玄冥，武冥，龟蛇合体。",
    promptZh: "生成一张山海经玄武插图，巨大的黑龟背负长蛇在北海之渊浮出水面，龟蛇交缠，黑色水波荡漾，玄武身上散发着玄冥的幽冷神光，中国四灵之玄武。",
    promptEn: "A divine Chinese Black Tortoise Xuan Wu, Shan Hai Jing illustration, enormous black turtle surfacing from northern sea depths with a long serpent coiling around it, turtle and snake intertwined, black waters rippling around, icy divine aura emanating from the creature, one of the Four Celestial Guardians, dark mysterious northern sea atmosphere, no text, no watermark",
    tags: ["四灵", "玄武", "北方"],
    bagua: "kan",
  },
  // 其他专题
  {
    id: "qi-lin",
    name: "麒麟",
    source: "《山海经》及各典籍",
    rawText: "麒麟，亦作"骐麟"，简称"麟"，是中国古籍中记载的一种动物，与凤、龟、龙共称为"四灵"，是神的坐骑。",
    promptZh: "生成一张麒麟瑞兽插图，麋鹿身形覆盖璀璨鳞甲，双角如枝杈般优雅伸展，蹄踏金色祥云，周身散发温润祥瑞光芒，背景是清晨朝霞中的山水长卷，中国传统祥瑞画风格。",
    promptEn: "A majestic Chinese Qilin unicorn, traditional Shan Hai Jing auspicious painting, graceful deer-like body covered in shimmering iridescent scales, branching antlers like coral, hooves stepping on golden auspicious clouds, warm gentle glow emanating from body, morning sunlit landscape backdrop, traditional Chinese lucky beast aesthetic, no text, no watermark",
    tags: ["祥瑞", "麒麟", "四灵"],
    bagua: "zhen",
  },
  {
    id: "bai-ze",
    name: "白泽",
    source: "《山海经》及各典籍",
    rawText: "昆仑山上著名的神兽，浑身雪白，能说人话，通万物之情，很少出没，除非当时有圣人治理天下，才奉书而至。",
    promptZh: "生成一张白泽神兽插图，通体雪白的仁瑞之兽，狮身羊角龙尾，头生如玉晶莹双角，站立于云雾缭绕的昆仑山巅，手中握有一卷天书，散发清冷高洁的神光，中国神话中的智慧祥瑞之兽。",
    promptEn: "A wise white Chinese auspicious beast Bai Ze, Shan Hai Jing illustration, pure white lion-like body with ram curved horns and dragon tail, translucent jade-like antlers on head, standing on cloud-shrouded Kunlun mountain peak, holding a celestial scroll in divine forepaws, cool silver-white divine glow, ancient Chinese mythological sage beast, no text, no watermark",
    tags: ["昆仑", "白泽", "祥瑞"],
    bagua: "kun",
  },
  {
    id: "kun-peng",
    name: "鲲鹏",
    source: "《庄子·逍遥游》",
    rawText: "北冥有鱼，其名为鲲。鲲之大，不知其几千里也。化而为鸟，其名为鹏。鹏之背，不知其几千里也，怒而飞，其翼若垂天之云。",
    promptZh: "生成一张鲲鹏插图，巨大无比的神鱼在北冥深海翻涌，鱼身遮蔽日光，化而为鹏展开垂天之翼，巨翼卷起云海风暴，鲲与鹏同框的瞬间转换，震撼人心的上古神话图景，中国水墨写意风格。",
    promptEn: "A colossal Chinese mythic Kun Fish transforming into Peng giant bird, Shan Hai Jing ink wash painting, enormous dark fish in deep northern sea with body blocking the sun, transitioning into giant bird with wings spanning like clouds across the horizon, wings creating storm winds and ocean waves, epic scale frozen in transformation moment, traditional Chinese ink wash art, no text, no watermark",
    tags: ["庄子", "鲲鹏", "化翼万里"],
    bagua: "kan",
  },
  {
    id: "feng-huang",
    name: "凤凰",
    source: "《山海经·南山经》",
    rawText: "丹穴之山，有鸟焉，其状如鸡，五采而文，名曰凤皇。首文曰德，翼文曰义，背文曰礼，膺文曰仁，腹文曰信。",
    promptZh: "生成一张凤凰神鸟插图，鸡头蛇颈燕颔龟背鱼尾五彩羽翼，羽毛赤橙黄白黑五色分明，翅膀展开百鸟来朝，背景是日出扶桑的神山，金光万道，中国祥瑞神话中的百鸟之王。",
    promptEn: "A divine Chinese Phoenix Feng Huang, Shan Hai Jing ancient illustration, bird with chicken head, snake neck, swallow chin, turtle back and fish tail, five-colored plumage in red orange yellow white black, wings spread wide as all birds bow in reverence, golden sunrise behind sacred Fusang mountain, rays of light cascading down, Chinese mythological king of birds, no text, no watermark",
    tags: ["南山经", "凤凰", "五德"],
    bagua: "li",
  },
  {
    id: "san-zu-wu",
    name: "三足乌",
    source: "各典籍综合记载",
    rawText: "三足乌又名三足金乌，中国古代神话中的神鸟，也称金乌、阳乌，或称三足。",
    promptZh: "生成一张三足乌金鸟插图，三只脚的金色乌鸦全身绽放太阳般的光芒，口中衔着一枝扶桑树树枝，背后是熊熊燃烧的太阳表面，十日并出的远古传说场景，中国上古太阳神话。",
    promptEn: "A divine Chinese three-legged Golden Crow, Shan Hai Jing ancient myth illustration, golden raven with three legs radiating sunlight, perched on a Fusang sacred tree branch, background showing the burning surface of the sun, scene depicting the ancient legend of ten suns, epic Chinese solar mythology, no text, no watermark",
    tags: ["太阳", "三足乌", "金乌"],
    bagua: "qian",
  },
  {
    id: "chong-ming",
    name: "重明鸟",
    source: "《山海经》及各典籍",
    rawText: "重明鸟，其形似鸡，鸣声如凤，此鸟两目都有两个眼珠，所以叫作重明鸟，亦叫重睛鸟。",
    promptZh: "生成一张重明鸟神鸟插图，外形像鸡却鸣声如凤，双眼各有两个瞳孔金光闪烁，巨爪抓碎恶兽，驱邪的姿态站立于门户之前，公鸡报晓般的清晨阳光，古代新年风俗中贴画鸡于门窗上的原型，中国神话辟邪之鸟。",
    promptEn: "A divine Chinese double-pupil bird Chong Ming, Shan Hai Jing auspicious illustration, rooster-like bird with two pupils in each eye glowing golden, talons crushing an evil beast beneath its feet, standing at a traditional Chinese doorframe at dawn, morning sun rays like a rooster crowing, ancient auspicious bird that wards off evil, no text, no watermark",
    tags: ["辟邪", "重明鸟", "重瞳"],
    bagua: "gen",
  },
  {
    id: "zuan-chi",
    name: "凿齿",
    source: "《山海经》及各典籍",
    rawText: "传说中居住在中国南部沼泽地带的怪兽或巨人。凿齿长有象凿子一样的长牙，这对长牙穿透他的下巴穿出，他手中持有盾和矛。",
    promptZh: "生成一张凿齿异兽插图，下巴穿出两根凿子般长牙的巨人形象，手持巨盾和长矛站立于沼泽之中，周围是荆棘和枯木，后羿射日弓箭手的剪影在远处，中国上古人与异兽激战场面。",
    promptEn: "A monstrous Chinese giant Zuan Chi, Shan Hai Jing ancient illustration, towering figure with two chisel-like fangs penetrating through the chin, holding a massive shield and spear, standing in a dark southern swamp surrounded by thorns and withered trees, archer silhouette in distance with bow drawn, epic battle scene from Chinese mythology, no text, no watermark",
    tags: ["南方", "凿齿", "持盾"],
    bagua: "zhen",
  },
  {
    id: "jiu-ying",
    name: "九婴",
    source: "《淮南子》高诱注",
    rawText: "九婴，水火之怪，为人害……北狄之地有凶水。九头怪物，名叫九婴，既能喷水，又能喷火。",
    promptZh: "生成一张九婴异兽插图，九个狰狞的婴儿头颅同时在一个躯体上，有的水中喷水有的火中吐火，九道水火交织的旋涡在身躯周围翻涌，背景是沸腾的凶水，北狄荒原的苍凉，中国上古水火凶兽图。",
    promptEn: "A terrifying nine-headed Chinese monster Jiu Ying, Shan Hai Jing ancient illustration, nine grotesque infant heads on a single serpentine body, each head either spitting water or breathing fire, nine swirling water and fire vortices surrounding the beast, standing in boiling black waters, desolate northern frontier backdrop, ancient Chinese mythological water-fire creature, no text, no watermark",
    tags: ["北方", "九婴", "水火"],
    bagua: "kan",
  },
  {
    id: "shu-hu",
    name: "孰湖",
    source: "《山海经·西山经》",
    rawText: "崦嵫之山，有兽焉，其状如马而鸟翼，名曰孰湖，见则其邑大水。",
    promptZh: "生成一张孰湖异兽插图，马身形却展开巨大的鸟翼盘旋于天穹，遮天蔽日，远处城邑即将被大水淹没，巨翼卷起海啸般的风暴，中国神话中马与鸟融合的巨型飞兽。",
    promptEn: "A colossal Chinese beast Shu Hu, Shan Hai Jing ancient illustration, horse-like creature with enormous bird wings spread across the sky, blocking out the sun, wings creating tsunami-like storm winds, city about to be flooded in distance, ominous powerful presence, Chinese mythological flying horse creature, no text, no watermark",
    tags: ["西山经", "孰湖", "兆水灾"],
    bagua: "li",
  },
];

// 合并所有异兽
export const ALL_CREATURES: Creature[] = [
  ...NANSHAN_CREATURES,
  ...XISHAN_CREATURES,
  ...BEISHAN_CREATURES,
  ...DONGSHAN_CREATURES,
  ...ZHONGSHAN_CREATURES,
  ...DAHUANG_CREATURES,
  ...HAIWAI_CREATURES,
  ...HAINEI_CREATURES,
  ...TOPIC_CREATURES,
];

// 按分类分组
export const CREATURES_BY_CATEGORY = {
  "南山经": NANSHAN_CREATURES,
  "西山经": XISHAN_CREATURES,
  "北山经": BEISHAN_CREATURES,
  "东山经": DONGSHAN_CREATURES,
  "中山经": ZHONGSHAN_CREATURES,
  "大荒经": DAHUANG_CREATURES,
  "海外经": HAIWAI_CREATURES,
  "海内经": HAINEI_CREATURES,
  "附录专题": TOPIC_CREATURES,
};

// 导出分类列表
export const CATEGORIES = Object.keys(CREATURES_BY_CATEGORY);